name: dart_log
description: Package for logging some info, warnings and errors.
version: 1.3.2
repository: https://github.com/yope-dev/dart_log

environment:
  sdk: ^3.1.2

# Add regular dependencies here.
dependencies:
  path: ^1.8.3

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
